### ISSUE TITLE
Enable CONFIG_YML overriding with individual properties

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/cf-ops-automation-broker#138]
As a cf service operator, I need to override the CONFIG_YML individual properties such as 

```yml
spring.cloud.openservicebroker.catalog.services[0].plans[0].metadata.costs[0].amount[eur]: (( grab secrets.coa-cf-mysql-broker.plan-coab-mariadb-price.small ))
spring.cloud.openservicebroker.catalog.services[0].plans[0].metadata.costs[1].amount[eur]: (( grab secrets.coa-cf-mysql-broker.plan-coab-mariadb-price.medium ))
spring.cloud.openservicebroker.catalog.services[0].plans[0].metadata.costs[2].amount[eur]: (( grab secrets.coa-cf-mysql-broker.plan-coab-mariadb-price.large ))
spring.cloud.openservicebroker.catalog.services[0].plans[0].metadata.costs[3].amount[eur]: (( grab secrets.coa-cf-mysql-broker.plan-coab-mariadb-price.xlarge ))
spring.cloud.openservicebroker.catalog.services[0].plans[0].metadata.costs[4].amount[eur]: (( grab secrets.coa-cf-mysql-broker.plan-coab-mariadb-price.xxlarge ))
spring.cloud.openservicebroker.catalog.services[0].plans[0].metadata.costs[5].amount[eur]: (( grab secrets.coa-cf-mysql-broker.plan-coab-mariadb-price.powerlarge ))
spring.cloud.openservicebroker.catalog.services[0].plans[0].metadata.costs[6].amount[eur]: (( grab secrets.coa-cf-mysql-broker.plan-coab-mariadb-price.capacitylarge ))
```

However, this currently fails with 

```
Caused by: org.springframework.boot.context.properties.bind.validation.BindValidationException: Binding validation errors on spring.cloud.openservicebroker.catalog.services[0]
    - Field error in object 'spring.cloud.openservicebroker.catalog.services[0]' on field 'id': rejected value [null]; codes [NotEmpty.spring.cloud.openservicebroker.catalog.services[0].id,NotEmpty.id,NotEmpty.java.lang.String,NotEmpty]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [spring.cloud.openservicebroker.catalog.services[0].id,id]; arguments []; default message [id]]; default message [must not be empty]
```

**Comment by gberche-orange** [comment]
Was workaround in v41 with spruce templating of the 

coab-depls/cf-apps-deployments/coa-cf-mysql-broker/template/coa-cf-mysql-broker_manifest-tpl.yml:

```yml
     # Override the default catalog
     CATALOG_YML: (( file "../../../../generated-files/broker-catalog-config.yml" ))
```

coab-depls/cf-apps-deployments/coa-cf-mysql-broker/template/broker-catalog-config-tpl.yml
```yml
servicebroker:
  catalog:
    services:
      - id: cf-mysql-ondemand-service
        name: cf-mysql-ondemand
        description: "MariaDB 10.1.38 databases on demand on dedicated Galera cluster "
        bindable: true
        plans:
          - id: plan-coab-mariadb-small
            name: small
            description: Dedicated MariaDB Galera Cluster 2GB data storage with 4GB RAM/1CPU
            free: false
            metadata:
              bullets:
                - 2GB storage
                - 50 concurrent connections
              costs:
                - amount:
                    eur: (( grab secrets.coa-cf-mysql-broker.plan-coab-mariadb-price.small ))
                  unit: Monthly
              displayName: Small Data 2GB - 4GB RAM/1CPU
[...]
```
