### ISSUE TITLE
Refine OSB metadata provided in coab-vars.yml & git commit message

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/cf-ops-automation-broker#171]
As of OSB spec 2.14 described in [CF profile](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#cloud-foundry-context-object), the org/space/service instance names are available in the context:

```yml
  "context": {
    "platform": "cloudfoundry",
    "organization_guid": "87505508-4c09-499e-933c-eb89582cb9a5",
    "space_guid": "30d49f4b-82bd-4e59-b90f-25a13a8a43dd",
    "organization_name": "system_domain",
    "space_name": "overview-broker",
    "instance_name": "my-service"
  },
```

Making it available to git commit message makes it more friendly for operators.
Making it available to coab-vars.yml enables templates authors to leverage it in their automation.
