### ISSUE TITLE
Conditional operators inclusion support

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/cf-ops-automation-broker#30]
As a service author, in order to support different service plans, and different arbitrary params, I need to conditionally include some bosh operators depending on OSB input data received during service provisionning or unprovisionning

Proposal:

Given a user input provided by coab as `coab-vars.yml` in #29 

```yml
---
deployment_name: "cassandravarsops_aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa0"
instance_id: "service_instance_id"
service_id: "service_definition_id"
plan_id: "smallguid123455"
context:
  platform: "cloudfoundry"
  user_guid: "user_guid1"
  space_guid: "space_guid1"
  organization_guid: "org_guid1"
parameters:
  cacheRatio: 0.8642
  cacheSizeMb: 10
  slowQuery: false
  roadmin: true
previous_values:
  plan_id: "previous_plan_guid"
```

and a service model with files ending with a suffix matching the `-when-<property>-equals-<value>`  where
* `<property>` designates the path to a key within the `coab-vars.yml` structure. Supported path include toplevel properties such as `plan_id`, or parameters top level keys such as `parameters.roadmin`
* `<value>` represents a value to match as string litteral such as `true` or `0.8642`

```sh
$ tree coab-depls/cloudfoundry-mysql/

coab-depls/cloudfoundry-mysql/
|-- deployment-dependencies.yml
`-- template
    |-- 03-add-roadmin-operators.yml-when-parameters.roadmin-equals-true -> ./cf-mysql-deployment/operations/add-roadmin.yml
    |-- 07-service-plan-small-operators.yml-when-planid-equals-smallguid123455 -> ./cf-mysql-deployment/operations/add-read-write-admin.yml
    |-- 08-kubernetes-binding-format-operators.yml-when-context.platform-equals-kubernetes
    |-- 08-cloudfoundry-binding-format-operators.yml-when-context.platform-equals-cloudfoundry
    |-- 10-enable-syslog-operators.yml -> ./cf-mysql-deployment/operations/enable-syslog.yml
    |-- cloudfoundry-mysql-vars-tpl.yml
    `-- 99-cloudfoundry-mysql.yml -> ./cf-mysql-deployment/cf-mysql-deployment.yml
```

then coab would generate conditionnally include the operators files depending on their matching of `coab-vars.yml` (while preserving systematic inclusion of other operators), resulting in the following coab bosh template directory

```
$ tree coab-depls/c_1c7d3610-6223-4d45-bc76-f027457a1253

c_1c7d3610-6223-4d45-bc76-f027457a1253/
|-- deployment-dependencies.yml
`-- template
    |-- 03-add-roadmin-operators.yml-> ../../cloudfoundry-mysql/template/03-add-roadmin-operators.yml-when-parameters.roadmin-equals-true
    |-- 07-service-plan-small-operators.yml -> ../../cloudfoundry-mysql/template/07-service-plan-small-operators.yml-when-planid-equals-smallguid123455
    |-- 08-cloudfoundry-binding-format-operators.yml -> ../../cloudfoundry-mysql/template/08-cloudfoundry-binding-format-operators.yml-when-context.platform-equals-cloudfoundry
    |-- 10-enable-syslog-operators.yml -> ./cf-mysql-deployment/operations/enable-syslog.yml -> ../../cloudfoundry-mysql/template/10-enable-syslog-operators.yml
    |-- cloudfoundry-mysql-vars-tpl.yml  -> ../../cloudfoundry-mysql/template/cloudfoundry-mysql-vars-tpl.yml
    `-- 99-cloudfoundry-mysql.yml -> ../../cloudfoundry-mysql/template/99-cloudfoundry-mysql.yml
```
