### ISSUE TITLE
Credhub & service binding support

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/cf-ops-automation-broker#41]
As a service author, I need to provide services without going through the burden of developping a service broker to generate service-specific credentials, instead I design my bosh release to support seeding some values (typically users and associated permissions), e.g. by scripting some usual CLIs.

Given a service author does not configure a nested broker endpoint in COAB configuration, then COAB provides a desired bindings hash to the bosh deployment in a bosh variable. Following the bosh deployment, the resulting binding credentials get returned (as string litterals or credhub references)  in the manifest.yml in the global properties section.

### Desired binding

For each service binding, COAB add a Coab-binding-\<guid\>-vars.yml file paas-templates repo in the service instance directory, whose content mimics the [binding endpoint payload](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#body-8)

```yml
---
bindings:
- <binding-guid>: 
   epoq:<epoq>.<timestamp> #epoq
   context:
     platform: "cloudfoundry"
     user_guid: "user_guid1"
     space_guid: "space_guid1"
     organization_guid: "org_guid1"
   parameters:
     userPermissions: read
# previous_values: # add this once osb supports binding updates
```

### Resulting binding credentials
 
Broker authors provide the following operator template with a well known name `Foreach-bindings-operators.yml` which manipulates the deployment manifest file, e.g. 
* declare new credhub user/passwords
* specify properties with user/passwords (that e.g. would trigger seeding of users in a database by the bosh job).
* specify binding credentials to be returned to user

```yml
---
# TODO: provide a realistic example of the Foreach-bindings-operators.yml
```

COAB expands a copy of this file for each service binding, the content of the template gets interpolated with "{0}" being replaced by a service binding Id. 
 
Binding responses gets recorded in the resulting manifest as coab.bindings.binding-guid and may contain literals and
credhub refs. When absent a credhub ref is returned to the binding path defined by convention 

```yml
---
# TODO: provide a realistic example of the resulting manifest.yml properties, with the credentials to return  in their different format
```

 
This credhub ref may contain the whole credentials response.
