### ISSUE TITLE
Metadata Plan not returned to cf

### ISSUE THREAD

**Issue by ldangeard-orange** [orange-cloudfoundry/cf-ops-automation-broker#49]
We describe plan in `coab-depls/cf-apps-deployments/coa-<produit>-broker/template/coa-<produit>-broker_manifest-tpl.yml` with metadata, for exemple

```yml
CATALOG_YML: |
          servicebroker:
            catalog:
              services:
              - id: cf-mysql-ondemand-service
                name: cf-mysql-ondemand
                description: "MariaDB databases on demand on dedicated Galera cluster "
                bindable: true
                plans:
                  - id: plan-coab-mariadb-small
                    name: small
                    description: Dedicated MariaDB Galera Cluster 2GB data storage with 4GB RAM/1CPU
                    free: false
                    metadata:
                      bullets:
                      - 2GB storage
                      - 50 concurrent connections
                      costs:
                      - amount:
                          eur: 48.0
                        unit: Monthly
                      displayName: Small Data 2GB - 4GB RAM/1CPU
```
We need to send this metadata to cf marketplace.
List of fields : https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#plan-metadata-fields
